apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ourtanzuapp.mydev.tap.20230727222442.0.0+build.13e7965
spec:
  refName: ourtanzuapp.mydev.tap
  version: 20230727222442.0.0+build.13e7965
  releaseNotes: |
    Release v20230727222442.0.0+build.13e7965 of package ourtanzuapp.mydev.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: us.gcr.io/daisy-284300/icg-vmware/build-service/workloads/ourtanzuapp-mydev-bundle@sha256:16e2e30703d04c8be50a7ed126b15107eedbb7c15ee1d1cb5ff7f5835b5fac65
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          description: Required. Name of the workload, used by K8s Ingress HTTP rules.
          default: ""
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 1
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned
        greeting:
          title: Greeting message
          type: string
          description: Greeting message for tanzu-java-web-app.
          default: all of you in Tanzu

