---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: mytanzuapp-pkgi
spec:
 serviceAccountName: default # ServiceAccount on Run cluster with permissions to deploy Package, see "Set up Run Cluster Namespaces"
 packageRef:
   refName: mytanzuapp.mydev.tap # name of the Package
   versionSelection:
     constraints: ">= 0.0.0-0"
 values:
 - secretRef:
     name: app-values # Secret created in previous step