apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: mytanzuapp.mydev.tap.20230707190716.0.0+build.eb56f16
spec:
  refName: mytanzuapp.mydev.tap
  version: 20230707190716.0.0+build.eb56f16
  releaseNotes: |
    Release v20230707190716.0.0+build.eb56f16 of package mytanzuapp.mydev.tap
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: northamerica-northeast2-docker.pkg.dev/app-last-mile/icg-artifacts/tap/build-service/workloads/mytanzuapp-mydev-bundle@sha256:ae8c956b3b5657c1f9e5395ad34926010a90c40f62dc0bd47b497d9fd223da00
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          description: Required. Name of the workload, used by K8s Ingress HTTP rules.
          default: ""
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 1
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned

