apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  annotations:
    tekton.dev/git-0: "https://github.com/"
type: kubernetes.io/basic-auth
stringData:
  username: izabelacg
  password: 

# How to patch service account with this secret (3 options below)

#  --param “gitops_ssh_secret=git-ssh” \

#namespace_provisioner:
#  default_parameters:
#    supply_chain_service_account:
#      secrets:
#        - git-ssh

# does not work if using namespace_provisioner
#kubectl patch serviceaccount default -n ${WORKLOAD_NAMESPACE} --patch '"secrets": [ { "name": "git-ssh" } ]'