---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-package-install-role
rules:
- apiGroups: ["data.packaging.carvel.dev"]
  resources: ["packages","packagemetadatas"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["packaging.carvel.dev"]
  resources: ["packageinstalls"]
  verbs: ["get", "list", "create", "update", "delete"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-permit-packages
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-package-install-role
subjects:
- kind: ServiceAccount
  name: default