apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-img-server.mydev.tap.20230630210856.0.0
spec:
  refName: tanzu-java-web-app-img-server.mydev.tap
  version: 20230630210856.0.0
  releaseNotes: |
    Release v20230630210856.0.0 of package tanzu-java-web-app-img-server.mydev.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: us.gcr.io/daisy-284300/icg-vmware/build-service/workloads/tanzu-java-web-app-img-server-mydev-bundle@sha256:41e5de17170a14ea4b5001be0634f2a9dd5b6f044942e8f7a21edbe5feb913bf
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          description: Required. Name of the workload, used by K8s Ingress HTTP rules.
          default: ""
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 1
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned

